<?php
defined( 'IN' ) || exit( 'Access Denied' );

$tmp_lang_set = [
	'zh' => [
		// Common
		'Operator' => '操作人',
		'Back' => '返回',
		'Add' => '添加',
		'Insert' => '插入',
		'Continue' => '繼續',
		'Edit' => '修改',
		'Update' => '更新',
		'Lock' => '鎖定',
		'Unlock' => '解鎖',
		'Last Operator' => '最後操作人',
		'Log' => '日誌',
		'Logs' => '日誌',
		'View' => '查看',
		'Title' => '標題',
		'Search' => '搜索',
		'Trash' => '回收站',
		'All' => '全部',
		'Total' => '總共',
		'Click to order by ID' => '點此以ID排序',
		'Click to order by last modification' => '點此按最後修改時間排序',
		'Click to order by' => '點擊以此排序',
		'Modified' => '最後修改',
		'Deleted' => '已刪除',
		'No list' => '列表爲空',
		'No result' => '無結果',
		'Notes' => '便箋',
		'Filename' => '文件名',
		'Description' => '描述',
		'Size' => '大小',
		'Dimension' => '尺寸',
		'Thumbnail' => '縮略圖',
		'Delete' => '刪除',
		'Filters' => '過濾',
		'Batch Operation' => '批量操作',
		'Categories' => '分類',
		'Category' => '分類',
		'Truename' => '姓名',
		'Added' => '創建時間',
		'Created' => '創建時間',
		'Updated' => '更新時間',
		'Save' => '保存',
		'Action' => '操作',
		'Error' => '錯誤',
		'Value' => '值',
		'Select' => '選擇',
		'File' => '文件',
		'Max size' => '大小上限',
		'page' => '頁',
		'Status' => '狀態',
		'Email' => 'Email',
		'keywords' => '關鍵詞',

		// Coldiy
		'Customize Columns' => '定製欄位',
		'Define Columns' => '定義欄位',
		'Add New Column' => '添加新欄位',
		'Priority' => '優先級',
		'Type' => '類型',
		'Optional values' => '可選值',
		'Disabled Groups' => '禁用的群組',
		'Read only' => '只讀',
		'The admin groups chosen won&#39;t be able to see this column.' => '選中的群組將不能看到這個欄位',
		'Dropdown Values' => '下拉值',
		'Member Group' => '用戶組',
		'Members in any of above groups will be selectable' => '上述群組的成員將列出以供選擇',
		'Mirror' => '鏡像',
		'Only when records&#39; IDs are same (other IDs column not supported yet)' => '僅當雙方ID相同時方可使用 (ID映射尚未支持)',
		'Only when records&#39; mapping IDs are different, need to set the next field column' => '僅當記錄的對應ID在數據表中不同列時，需要設置下一個輸入框',
		'Mirror mapping ID of current table' => '當前數據表的映射ID',
		'Update Column Data' => '更新欄位值',
		'Column' => '欄位',
		'Assign to Me' => '分配給自己',
		'Unassign' => '未分配',
		'Address' => '地址',
		'Web Address' => '網頁地址',
		'Text to Display' => '顯示文字',
		'URL' => '網址',
		'Text' => '文字',
		'This will add a reverse search option to filters' => '這將會在過濾器中增加一個反向搜尋框',
		'Reverse Search' => '反向搜尋',
		'Reverse' => '非',

		// Filters
		'Filter' => '過濾',
		'Any Person' => '任意成員',
		'Me' => '自己',
		'Start' => '開始',
		'End' => '結束',
		'Click to remove this filter' => '點擊移除本過濾',

		// core.js
		'Please confirm you want to proceed' => '請確認您要執行本次操作嗎？',
		'Failed to clear column value' => '清空欄位值失敗',
		'Failed to update column value' => '更新欄位值失敗',
		'Copied' => '已複製',
		'Shortcut' => '快捷鍵',

		// menu.cfg.php
		'System' => '系統',
		'Admins' => '後臺用戶',
		'Groups' => '群組',
		'Languages' => '語言包',

		// lang.add.html
		'String' => '字符串',
		'Chinese Translation' => '中文翻譯',

		// Login
		'Mobile Verify' => '手機驗證',
		'Dynamic code has sent to' => '動態驗證碼已發往',
		'2FA Verify' => '2FA認證',
		'Mobile Text' => '手機短信',
		'Dynamic code' => '動態驗證碼',
		'2FA Code' => '2FA 驗證碼',
		'Enable 2FA' => '開啓2FA',
		'Verify' => '驗證',
		'Log In' => '登入',
		'Username' => '用戶名',
		'Password' => '密碼',
		'Login' => '登入',
		'Set 2FA successfully.' => '成功設置2FA認證',
		'2FA code is wrong' => '2FA認證檢查失敗',
		'Please scan this barcode w/ your phone 2FA app (e.g. Google Authenticator) and type the code in 2FA app below' => '請用您手機的2FA應用掃描本條形碼 (比如Google Authenticator)並輸入2FA手機應用所提供的驗證碼',
		'Barcode' => '條形碼',

		// login.profile.html
		'UserName' => '用戶名',
		'Logoff' => '登出',
		'Old Password' => '舊密碼',
		'New Password' => '新密碼',
		'Avatar' => '頭像',
		'Random Avatar' => '隨機頭像',
		'JPG/PNG only. Max size 2M.' => '僅允許JPG/PNG. 最大尺寸 2M.',
		'Upload' => '上傳',
		'Login Security' => '登錄安全',
		'Switch to Mobile Dynamic Code Login' => '切換到手機動態驗證碼登錄',
		'Clear 2FA login will switch back to mobile dynamic code to login.' => '清除2FA登錄將切換回手機動態驗證碼登錄',
		'This will generate a new QR code. The previous 2FA will become invalid.' => '點擊將生成一個新的二維碼。之前的2FA將會失效。',
		'Please make sure you installed Google Authenticator app on your phone before switching.' => '點擊切換之前請確保手機已安裝Google Authenticator app',
		'Switch to 2FA Login' => '切換爲2FA登錄',

		// ps
		'Add a Note to' => '添加新便籤到',
		'Note' => '便籤',
		'Add Note' => '添加便籤',
	],
];

define( 'LANG_SET', array_change_key_case( $tmp_lang_set[ LANG == 'en' ? 'zh' : LANG ] ) );
